---
title: "Week 7 (02-06-25 to 06-06-25)"
editor: visual
---

## Prepare

📖 Read the [syllabus](/course-syllabus.html)

📖 Read the [support](/course-support.html) resources

## Participate

🖥️[Lecture 3](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_3.pptx) - Continuous Probability Distributions

```{=html}
<iframe src="https://view.officeapps.live.com/op/embed.aspx?src=https%3A%2F%2Fraw%2Egithubusercontent%2Ecom%3A443%2FMayooran1987%2FMC3020%2DE23%2Frefs%2Fheads%2Fmain%2FLect%5F3%2Epptx&amp;wdAr=1.3333333333333333" width="1026px" height="793px" frameborder="0">This is an embedded <a target="_blank" href="https://office.com">Microsoft Office</a> presentation, powered by <a target="_blank" href="https://office.com/webapps">Office</a>.</iframe>
```

🖥️ [Statistical Table](https://github.com/Mayooran1987/MC3020-E23/raw/main/Statistical_table_MC3020.pdf) - Statistical Table for probability estimations.

🖥️ [Lecture 2](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_2.pptx) - Discrete Probability Distributions

🖥️ [Lecture 1](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_1.pptx) - Introduction to Probability

## Practice

1.  Consider a civil engineering project where traffic flow at a certain intersection needs to be analyzed. The number of vehicles waiting at a traffic signal follows the following probability distribution:

    |           |      |     |      |      |      |      |
    |-----------|------|-----|------|------|------|------|
    | X = x     | 1    | 2   | 3    | 4    | 5    | 6    |
    | P (X = x) | 0.20 | k   | 0.25 | 0.10 | 0.10 | 0.05 |

    Here, z represents the number of vehicles waiting, and P(X = x) is the probability of observing vehicles waiting. Given this information, let’s solve the following questions:

    a)  Determine the value of k.
    b)  Estimate the expected number and standard deviation of vehicles waiting at the traffic signal.
    c)  What is the probability that fewer than three vehicles are waiting at the traffic signal?
    d)  What is the probability that at least four vehicles are waiting at the traffic signal?

2.  In the November 1990 issue of Chemical Engineering Progress, a study discussed the percent purity of oxygen from a certain supplier. Assume that the mean was 99.61 with a standard deviation of 0.08. Assume that the distribution of percent purity was approximately normal.

    a)  What percentage of the purity values would you expect to be between 99.5 and 99.7?
    b)  What purity value would you expect to exceed exactly 5% of the population?

3.  High accumulation of certain pollutants in the atmosphere can adversely affect the environment and human health, which is a concern for the Ariviyal Nagar region, particularly the vicinity of the University of Jaffna. Elevated levels of pollutants such as particulate matter, sulphur dioxide, and nitrogen oxides can lead to respiratory issues and environmental degradation. Nitrogen oxides (NOx) are primary contributors to air pollution, primarily originating from vehicle emissions, industrial processes, and the combustion of fossil fuels. Suppose the distribution of nitrogen oxide emissions from vehicles in the Ariviyal Nagar region can be modelled adequately by a normal distribution with a mean emission level (μ) of 80 ppb (parts per billion) and standard deviation(σ) of 12 ppb.

    a)  What is the probability that a randomly selected vehicle from the Ariviyal Nagar region will have emission levels less than 50 ppb?
    b)  What is the probability that a randomly selected vehicle from the Ariviyal Nagar region will have emission levels greater than 100 ppb?
    c)  What is the probability that a randomly selected vehicle from the Ariviyal Nagar region will have emission levels between 40 ppb and 116 ppb?

4.  The operator of a pumping station has observed that demand for water during early afternoon hours follows an approximately exponential distribution with a mean of 100 cubic feet per second (cfs).

    a)  Find the probability that the demand will exceed 200 cfs during the early afternoon on a randomly selected day.
    b)  What water-pumping capacity should the station maintain during the early afternoons so that the probability that demand will exceed capacity on a randomly selected day is only 0.01?

5.  The heights of 1000 students are approximately normally distributed with a mean of 174.5 centimetres and a standard deviation of 6.9 centimetres. Suppose 200 random samples of size 25 are drawn from this population and the means are recorded to the nearest tenth of a centimetre. Determine

    a)  the mean and standard deviation of the sampling distribution of $\bar{X}$.

    b)  the number of sample means falling below 172.0 centimeters.

    c)  the number of sample means that fall between 172.5 and 175.8 centimeters inclusive.

## Perform

Assignment 2 Examination is postponed to Monday (09-06-2025).

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
