---
title: "Week 2 (15-12-25 to 19-12-25)"
editor: visual
---

## Prepare

📖 Read the [syllabus](/course-syllabus.html)

📖 Read the [support](/course-support.html) resources

## Participate

🖥️ [Lecture 2](https://github.com/Mayooran1987/MC3020_E24/raw/main/Lect_2.pptx) - Discrete Probability Distributions

```{=html}
<iframe src="https://view.officeapps.live.com/op/embed.aspx?src=https%3A%2F%2Fraw%2Egithubusercontent%2Ecom%3A443%2FMayooran1987%2FMC3020%2DE23%2Frefs%2Fheads%2Fmain%2FLect%5F2%2Epptx&amp;wdAr=1.3333333333333333" width="1026px" height="793px" frameborder="0">This is an embedded <a target="_blank" href="https://office.com">Microsoft Office</a> presentation, powered by <a target="_blank" href="https://office.com/webapps">Office</a>.</iframe>
```

🖥️ [Statistical Table](https://github.com/Mayooran1987/MC3020_E24/raw/main/Statistical_table_MC3020.pdf) - Statistical Table for probability estimations.

🖥️ [Lecture 1](https://github.com/Mayooran1987/MC3020_E24/raw/main/Lect_1.pptx) - Introduction to Probability

## Practice

📋 Practice Problems

1)  A truth serum has the property that 90% of the guilty suspects are properly judged while, of course, 10% of the guilty suspects are improperly found innocent. On the other hand, innocent suspects are misjudged 1% of the time. If the suspect was selected from a group of suspects of which only 5% have ever committed a crime, and the serum indicates that he is guilty, what is the probability that he is innocent?

2)  A construction company employs two sales engineers. Engineer 1 does the work of estimating cost for 70% of jobs bid by the company. Engineer 2 does the work for 30% of jobs bid by the company. It is known that the error rate for engineer 1 is such that 0.02 is the probability of an error when he does the work, where as the probability of an error in the work of engineer 2 is 0.04. Suppose a bid arrives and a serious error occurs in estimating cost. Which engineer would you guess did the work? Explain and show all work.

3)  A group of 10 people consists of 3 managers and 7 employees. A team of 4 people to be selected randomly. What is the probability that

    a)  the team includes exactly 1 manager.
    b)  the team has at least 1 manager.
    c)  the team has 3 managers and 1 employee.

4)  A game involves drawing cards from three decks. Deck A has 3 blue cards and 2 green cards. Deck B contains 4 blue and 1 green cards. Deck C comprises 5 blue cards. A card is drawn from Deck A and placed in Deck C. A card from Deck B is drawn and placed in Deck C. Finally, a card is drawn from Deck C.

    a)  Draw a tree diagram to illustrate this game with all probabilities
    b)  Calculate the probability that exactly two green cards are drawn.
    c)  Given that two green cards are drawn, find the probability that the card from Deck A is blue.

5)  In an organization of 300 staff, they are divided among departments like this:

    |        | Design | Production | Quality Control |
    |:------:|:------:|:----------:|:---------------:|
    |  Male  |   60   |     80     |       40        |
    | Female |   50   |     40     |       30        |

    a)  What is the probability of selecting a Production employee given that a male was selected?

    b)  What is the probability of selecting a male given that a Design employee was selected?

    c)  If we randomly select one employee, let X be the event that the selected employee is a female and Y be the event that the selected employee is from the Quality control. Are events X and Y mutually exclusive?

<!-- ## Perform -->

<!-- ⌨️ [Lab 0 - Meet + greet](/labs/lab-0.html) -->

<br><br>

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
