---
title: "Week 1 (08-12-25 to 12-12-25)"
subtitle: "Welcome to MC3020"
editor: visual
---

## Prepare

📖 Read the [syllabus](/course-syllabus.html)

📖 Read the [support](/course-support.html) resources

## Participate

🖥️ [Lecture 1](https://github.com/Mayooran1987/MC30200_E2/raw/main/Lect_1.pptx) - Introduction to Probability

```{=html}
<iframe src="https://view.officeapps.live.com/op/embed.aspx?src=https%3A%2F%2Fraw%2Egithubusercontent%2Ecom%3A443%2FMayooran1987%2FMC3020%5FE24%2Frefs%2Fheads%2Fmain%2FLect%5F1%2Epptx&amp;wdAr=1.3333333333333333" width="1026px" height="793px" frameborder="0">This is an embedded <a target="_blank" href="https://office.com">Microsoft Office</a> presentation, powered by <a target="_blank" href="https://office.com/webapps">Office</a>.</iframe>
```

## Practice

📋 Practice Problems

1.  In a batch of 100 final-year engineering students, 54 took Robotics as an optional subject, 69 took Environmental Engineering as an optional subject, and 35 took both Robotics and Environmental Engineering. If one of these students is selected at random, find the probability that:

    a)  the student took Robotics or Environmental Engineering.
    b)  the student did not take either of these subjects.
    c)  the student took Environmental Engineering but not Robotics.

2.  From past experience, a stockbroker believes that under present economic conditions a customer will invest in tax-free bonds with a probability of 0.6, will invest in mutual funds with a probability of 0.3, and will invest in both tax-free bonds and mutual funds with a probability of 0.15. At this time, find the probability that a customer will invest

    a)  in either tax-free bonds or mutual funds.
    b)  in neither tax-free bonds nor mutual funds.
    c)  given that a customer invests in mutual funds, what is the probability that they also invest in tax-free bonds?

3.  Interest centers around the life of an electronic component. Suppose it is known that the probability that the component survives for more than 6000 hours is 0.42. Suppose also that the probability that the component survives no longer than 4000 hours is 0.04.

    a)  What is the probability that the life of the component is less than or equal to 6000 hours?
    b)  What is the probability that the life is greater than 4000 hours.

4.  One bag contains 4 white balls and 3 black balls, and a second bag contains 3 white balls and 5 black balls. One ball is drawn from the first bag and placed unseen in the second bag. What is the probability that a ball now drawn from the second bag is black?

5.  A random sample of 200 adults are classified below by sex and their level of education attained.

    | Education  | Male | Female |
    |:----------:|:----:|:------:|
    | Elementary |  38  |   45   |
    | Secondary  |  28  |   50   |
    |  College   |  22  |   17   |

    (a) Find the probability that the person is a male, given that the person has a secondary education.
    (b) Find the probability that the person does not have a college degree, given that the person is a female.

6.  In an office there are two boxes of thumb drives: Box A~1~ contains seven 100GB drives and three 500 GB drives, and box A~2~ contains two 100 GB drives and eight 500 GB drives. A person is handed a box at random with prior probabilities P(A~1~) = 2/3 and P(A~2~) = 1/3 , possibly due to the boxes’ respective locations. A drive is then selected at random and the event B occurs if it is a 500 GB drive. Using an equally likely assumption for each drive in the selected box, compute P(A~1~\|B) and P(A~2~\|B).

<!-- ## Perform -->

<!-- ⌨️ [Lab 0 - Meet + greet](/labs/lab-0.html) -->

<br><br>

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
