---
title: "Week 13 (14-07-25 to 18-07-25)"
editor: visual
---

## Prepare

📖 Read the [syllabus](/course-syllabus.html)

📖 Read the [support](/course-support.html) resources

## Participate

🖥️[Lecture 5](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_5.pptx) - Statistical Inferences II

```{=html}
<iframe src="https://view.officeapps.live.com/op/embed.aspx?src=https%3A%2F%2Fraw%2Egithubusercontent%2Ecom%3A443%2FMayooran1987%2FMC3020%2DE23%2Fmain%2FLect%5F5%2Epptx&amp;wdAr=1.3333333333333333" width="1026px" height="793px" frameborder="0">This is an embedded <a target="_blank" href="https://office.com">Microsoft Office</a> presentation, powered by <a target="_blank" href="https://office.com/webapps">Office</a>.</iframe>
```

🖥️ [Statistical Table](https://github.com/Mayooran1987/MC3020-E23/raw/main/Statistical_table_MC3020.pdf) - Statistical Table for probability estimations.

🖥️[Lecture 4](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_4.pptx) - Statistical Inferences I

🖥️[Lecture 3](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_3.pptx) - Continuous Probability Distributions

🖥️ [Lecture 2](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_2.pptx) - Discrete Probability Distributions

🖥️ [Lecture 1](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_1.pptx) - Introduction to Probability

## Practice

1.  Please work on these problems (given in the [Practice problems](https://github.com/Mayooran1987/MC3020-E23/raw/main/Practice_1_MC3020_E23.pdf)) during the lecture session from 08:00 to 08:50 AM on Tuesday, July 15th. If needed, instructors will discuss the solutions and address any questions in the following lecture slot on the same day.

    🖥️ [Practice problems](https://github.com/Mayooran1987/MC3020-E23/raw/main/Practice_1_MC3020_E23.pdf)

2.  The Edison Electric Institute has published figures on the number of kilowatt hours used annually by various home appliances. It is claimed that a vacuum cleaner uses an average of 46 kilowatt hours per year. If a random sample of 12 homes included in a planned study indicates that vacuum cleaners use an average of 42 kilowatt hours per year with a standard deviation of 11.9 kilowatt hours, does this suggest at the 0.05 level of significance that vacuum cleaners use, on average, less than 46 kilowatt hours annually? Assume the population of kilowatt hours to be normal.

3.  A manufacturer of sports equipment has developed a new synthetic fishing line that the company claims has a mean breaking strength of 8 kilograms with a standard deviation of 0.5 kilograms. Test the hypothesis that $\mu=8$ kilograms against the alternative that $\mu=8$ kilograms if a random sample of 50 lines is tested and found to have a mean breaking strength of 7.8 kilograms. Use a 0.01 level of significance.

4.  Past data indicate that the amount of money contributed by the working residents of a large city to a volunteer rescue squad is a normal random variable with a standard deviation of $\$1.40$. It has been suggested that the contributions to the rescue squad from just the employees of the sanitation department are much more variable. If the contributions of a random sample of 12 employees from the sanitation department have a standard deviation of $\$1.75$, can we conclude at the 0.01 level of significance that the variance of the contributions of all sanitation workers is greater than that of all workers living in the city?

    a.  A factory produces 80,000 pistons daily. The acceptable defect rate is 0.8%. From a sample of 600 pistons, 1.2% were found defective.

    b.  Estimate the proportion of defective pistons in the sample.

    c.  Construct a 95% confidence interval for the true proportion of defective pistons.

    d.  Test whether the defect rate is higher than 0.8% at a 5% significance level.

    e.  Does the confidence interval support the hypothesis test conclusion?

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
