---
title: "Week 15 (28-07-25 to 01-08-25)"
editor: visual
---

## Prepare

📖 Read the [syllabus](/course-syllabus.html)

📖 Read the [support](/course-support.html) resources

## Participate

### **Lecture Schedule**

-   **Monday:**

    -   1:55 PM – 2:50 PM and 3:10 PM – 4:05 PM

-   **Tuesday:**

    -   8:00 AM – 8:55 AM and 8:55 AM – 9:50 AM

-   **Thursday:**

    -   8:00 AM – 8:55 AM and 8:55 AM – 9:50 AM

🖥️[Lecture 6](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_6.pptx) - Association between Two Variables

```{=html}
<iframe src="https://view.officeapps.live.com/op/embed.aspx?src=https%3A%2F%2Fraw%2Egithubusercontent%2Ecom%3A443%2FMayooran1987%2FMC3020%2DE23%2Frefs%2Fheads%2Fmain%2FLect%5F6%2Epptx&amp;wdAr=1.3333333333333333" width="1026px" height="793px" frameborder="0">This is an embedded <a target="_blank" href="https://office.com">Microsoft Office</a> presentation, powered by <a target="_blank" href="https://office.com/webapps">Office</a>.</iframe>
```

🖥️ [Statistical Table](https://github.com/Mayooran1987/MC3020-E23/raw/main/Statistical_table_MC3020.pdf) - Statistical Table for probability estimations.

🖥️[Lecture 5](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_5.pptx) - Statistical Inferences II

🖥️[Lecture 4](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_4.pptx) - Statistical Inferences I

🖥️[Lecture 3](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_3.pptx) - Continuous Probability Distributions

🖥️ [Lecture 2](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_2.pptx) - Discrete Probability Distributions

🖥️ [Lecture 1](https://github.com/Mayooran1987/MC3020-E23/raw/main/Lect_1.pptx) - Introduction to Probability

## Practice

1.  You are a mechanical engineer working in the automotive industry, tasked with optimizing the performance of internal combustion engines. A key performance metric you are focusing on is the thermal efficiency of the engines, which is influenced by the compression ratio - a critical design parameter. To better understand this relationship and aid in the design of more efficient engines, you collected data from various engine models. The data includes the compression ratio of the engines and their corresponding thermal efficiency percentages, as shown below:

    Compression Ratio : 8.5, 9.6, 10.1, 11.2, 12.1, 13

    Thermal Efficiency(%) : 31, 35, 42, 45, 56, 55

    a)  Create a scatter plot of the data points, with the compression ratio on the x-axis and thermal efficiency on the y-axis.
    b)  Determine the equation of the least squares regression line for predicting thermal efficiency based on the compression ratio. Explain the meaning of the slope and intercept coefficients in the context of the problem.
    c)  Use the regression line equation to predict the thermal efficiency for an engine with a compression ratio of 10.5.
    d)  Calculate the correlation (r) between compression ratio and thermal efficiency. Interpret the correlation value.
    e)  Conduct a hypothesis test at a 95% confidence level to determine whether the regression line is statistically significant. State the hypotheses, test statistic, and conclusion.( Hint: Standard error (Se)= 2.8521)
    f)  Discuss any assumptions or limitations of the linear regression model in this context.

2.  A study was done to study the effect of ambient temperature x on the electric power consumed by a chemical plant y, other factors were held constant and the data were collected from an experimental pilot plant.

    |         |                                 |
    |---------|---------------------------------|
    | Y (BTU) | 250 285 320 295 265 298 267 321 |
    | X (°F)  | 27 45 72 58 31 60 31 74         |

    a.  Compute and interpret the sample correlation coefficient.
    b.  Determine the equation of the least squares regression line for predicting power consumption on ambient temperature.
    c.  Predict power consumption for an ambient temperature of 65°F.
    d.  Calculate the coefficient of determination (R-squared) for the regression line and interpret its meaning.
    e.  Test the significance of the correlation coefficient (use $\alpha$ = 0.05).
    f.  Determine 95% confidence interval for the slope $\beta_1$.
    g.  Obtain 95% prediction interval for predicting a single response y for a specific value x = 50.
    h.  Obtain 95% confidence interval for the mean response at x=50.

::: {style="font-size: 0.875em;"}
Back to [course schedule](/ "Course schedule") ⏎
:::
